#pragma once

#define CMAKE_VERSION "@CMAKE_VERSION@"
#define PROJECT_NAME "@CMAKE_PROJECT_NAME@"
#define PROJECT_VERSION "@PROJECT_VERSION@"
#define C_VERSION "@CMAKE_C_STANDARD@"
#define CXX_VERSION "@CMAKE_CXX_STANDARD@"
#define BUILD_TYPE "@CMAKE_BUILD_TYPE@"
#define BUILD_DATE "@BUILD_DATE@"
#define BUILD_TIME "@BUILD_TIME@"
#define BUILD_DATE_TIME "@BUILD_DATE_TIME@"
